from .nodes import LTXMSRICLoRAFLF

NODE_CLASS_MAPPINGS = {
    "LTXMSRICLoRAFLF": LTXMSRICLoRAFLF
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "LTXMSRICLoRAFLF": "🅛🅣🅧 MSR IC LORA FLF (Standalone)"
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
